apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bigbears-commerce.fullname" . }}-client
  labels:
    {{- include "bigbears-commerce.labels" . | nindent 4 }}
    app.kubernetes.io/type: client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      {{- include "bigbears-commerce.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/type: client
  template:
    metadata:
      labels:
        {{- include "bigbears-commerce.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: client
    spec:
      {{- with .Values.client.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}