apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigbears-commerce.fullname" . }}-client
  labels:
    {{- include "bigbears-commerce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bigbears-commerce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/type: client