apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigbears-commerce.fullname" . }}
  labels:
    {{- include "bigbears-commerce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bigbears-commerce.selectorLabels" . | nindent 4 }}